name: build

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2016
    timeout-minutes: 9999

    steps:
    - name: Downloading resources
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/freljordfrost/AWS_RDP/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://javadl.oracle.com/webapps/download/AutoDL?BundleId=245477_4d5417147a92418ea8b615e228bb6935 -OutFile jre.exe
        Invoke-WebRequest https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/microemu/microemulator-2.0.4.zip -OutFile microemulator.zip
        Invoke-WebRequest https://angelchip.net/files/share/NSOAngelChip.jar -OutFile NSOAngelChip.jar
        Invoke-WebRequest https://vietup.net/taivett/deadeyes-jar/276536 -Outfile NSOD.jar
    - name: Extracting resources
      run: Expand-Archive ngrok.zip
    - name: Setting up Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Setting up RDP
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Setting up Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region=ap 3389"'
    - name: Setting up VPS
      run: cmd /c start.bat
    - name: VPS ready
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/freljordfrost/AWS_RDP/main/loop.bat -OutFile loop.bat
        cmd /c loop.bat
